package handlers

import (
	_ "github.com/closable/go-yandex-loyalty/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// InitRouter Инициализация маршрутов приложения
func (ah *APIHandler) InitRouter() chi.Router {
	router := chi.NewRouter()

	router.Post("/api/user/register", ah.Register)
	router.Post("/api/user/login", ah.Login)

	router.Mount("/debug", Profiler())
	router.Get("/swagger/*", httpSwagger.WrapHandler)

	router.Group(func(r chi.Router) {
		r.Use(ah.Authenticator)
		r.Get("/api/user/orders", ah.Orders)
		r.Post("/api/user/orders", ah.AddOrder)
		r.Post("/api/user/balance/withdraw", ah.GetWithdraw)
		r.Get("/api/user/withdrawals", ah.Withdrawals)
		r.Get("/api/user/balance", ah.Balance)
	})

	return router
}
